# Generated by Django 4.2.9 on 2024-01-27 02:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date of Dream')),
                ('name', models.CharField(max_length=100)),
                ('about', models.TextField(max_length=500)),
                ('feeling', models.CharField(choices=[('G', 'great'), ('O', 'okay'), ('N', 'not good'), ('B', 'terrible')], default='G', max_length=1)),
                ('dream_type', models.CharField(choices=[('N', 'nightmare'), ('A', 'dream'), ('W', 'weird dream')], default='nightmare', max_length=1)),
                ('owner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='dreams', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Palette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color1', models.CharField(max_length=7)),
                ('color2', models.CharField(max_length=7)),
                ('color3', models.CharField(max_length=7)),
                ('color4', models.CharField(max_length=7)),
                ('color5', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('dream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.dream')),
            ],
        ),
    ]
