# Generated by Django 4.2.9 on 2024-02-06 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Palette',
        ),
    ]
